create database vitoria_lanches;
use vitoria_lanches;

create table tb_usuarios
(
	TB_USUARIOS_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	TB_USUARIOS_USERNAME VARCHAR(20) NOT NULL UNIQUE,
    TB_USUARIOS_PASSWORD VARCHAR(20) NOT NULL,
    TB_USUARIOS_TIPO VARCHAR(20) NOT NULL
);

create table tb_cliente
(
	TB_CLIENTE_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TB_CLIENTE_NOME VARCHAR(128) NOT NULL,
    TB_CLIENTE_TEL VARCHAR(32) NOT NULL,
    TB_CLIENTE_ENDERECO VARCHAR(128),
    TB_CLIENTE_ENDERECO_NUM VARCHAR(8),
    TB_USER_FK INTEGER NOT NULL,
    FOREIGN KEY(TB_USER_FK) REFERENCES tb_usuarios(TB_USUARIOS_ID)
);


create table tb_pedido_venda
(
	TB_PEDIDO_VENDA_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TB_CLIENTE_ID INTEGER NOT NULL,
    TB_PEDIDO_VENDA_DATA DATETIME NOT NULL,
    TB_PEDIDO_VENDA_VAL_TOTAL DECIMAL(10,2) NOT NULL,
    TB_PEDIDO_VENDA_STATUS VARCHAR(16) NOT NULL,
    TB_PEDIDO_VENDA_FORMA_PAG VARCHAR(32) NOT NULL,
    TB_PEDIDO_VENDA_OBS VARCHAR(500),
    FOREIGN KEY(TB_CLIENTE_ID) REFERENCES tb_cliente(TB_CLIENTE_ID)
);

create table tb_tipo_produto
(
	TB_TIPO_PRODUTO_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TB_TIPO_PRODUTO_DESC VARCHAR(32) NOT NULL
);

create table tb_produto
(
	TB_PRODUTO_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TB_PRODUTO_NOME VARCHAR(128) NOT NULL,
    TB_TIPO_PRODUTO_ID INTEGER NOT NULL,
    TB_PRODUTO_DESC VARCHAR(512),
    TB_PRODUTO_PRECO_UNIT DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (TB_TIPO_PRODUTO_ID) REFERENCES tb_tipo_produto(TB_TIPO_PRODUTO_ID)
);

create table tb_pedido
(
	TB_PEDIDO_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TB_PRODUTO_ID INTEGER NOT NULL,
    TB_PEDIDO_VENDA_ID INTEGER NOT NULL,
    TB_PEDIDO_PRODUTO_QTD INTEGER NOT NULL,
    TB_PEDIDO_PRODUTO_PRECO_UNIT DECIMAL(10,2) NOT NULL,
    TB_PEDIDO_PRODUTO_PRECO_TOTAL DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (TB_PRODUTO_ID) REFERENCES tb_produto(TB_PRODUTO_ID), 
    FOREIGN KEY (TB_PEDIDO_VENDA_ID) REFERENCES tb_pedido_venda(TB_PEDIDO_VENDA_ID) 
);


alter table tb_pedido_venda
modify column TB_PEDIDO_VENDA_VAL_TOTAL DECIMAL(10,2);

insert into tb_usuarios
(
	TB_USUARIOS_USERNAME,
    TB_USUARIOS_PASSWORD,
    TB_USUARIOS_TIPO
) VALUES (
	'root',
    'root',
    'administrador'
);

select * from tb_usuarios;
select * from tb_cliente;
select * from tb_produto;

insert into tb_tipo_produto (TB_TIPO_PRODUTO_DESC) VALUES ('lanche');


drop database vitoria_lanches;